metadataURL: "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=PRJEB5348&result=read_run&fields=run_accession,fastq_ftp&format=tsv&download=true"

sampleMappingURL: "https://ndownloader.figshare.com/files/2194841"

conditions:
 - "WT"
 - "SNF2"

biologicalReplicates:
 - 1
 - 2
 - 3

genomeFASTA: "/home/luce/angsd/referenceGenomes/sacCer3.fa"

txomeGTF: "/home/luce/angsd/referenceGenomes/sacCer3.sgd.gtf"

tmpDir: "/scratchLocal/mef3005"
